services:
  - type: web
    name: taiwanewshorts
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python src/api/app.py
    envVars:
      - key: PORT
        value: 10000
      - key: PYTHONPATH
        value: /opt/render/project/src
